version: 2
updates:
  - package-ecosystem: "cargo"
    directory: "/"
    open-pull-requests-limit: 30
    schedule:
      interval: "daily"
      time: "07:10" # UTC
    commit-message:
      prefix: "chore(cargo):"
    target-branch: "develop"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "ci(actions):"
    target-branch: "develop"